# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-PTQkbSx9i_VqSGCy4phCXyHy02eTijt
"""

from google.colab import drive
drive.mount('/content/drive')

import os

dataset_path = "/content/drive/MyDrive/Emotion_Project/datasets/TESS Toronto emotional speech set data"

print(os.path.exists(dataset_path))

# ============================================================
# INSTALL REQUIRED PACKAGES
# ============================================================

!pip install -q transformers==4.41.2
!pip install -q scikit-learn seaborn tqdm

# ============================================================
# IMPORTS
# ============================================================

import os
import json
import random
import warnings

import numpy as np
import pandas as pd

from tqdm import tqdm

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split

from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix,
    precision_score,
    recall_score,
    f1_score
)

from sklearn.manifold import TSNE

import torch
import torch.nn as nn

from torch.utils.data import (
    Dataset,
    DataLoader
)

from transformers import (
    BertTokenizer,
    BertModel
)

warnings.filterwarnings("ignore")

# ============================================================
# RANDOM SEED
# ============================================================

SEED = 42

random.seed(SEED)
np.random.seed(SEED)

torch.manual_seed(SEED)

if torch.cuda.is_available():
    torch.cuda.manual_seed_all(SEED)

# ============================================================
# DEVICE
# ============================================================

DEVICE = torch.device(
    "cuda" if torch.cuda.is_available() else "cpu"
)

print("Device:", DEVICE)

# ============================================================
# PATHS
# ============================================================

DATASET_PATH = (
    "/content/drive/MyDrive/Emotion_Project/datasets/"
    "TESS Toronto emotional speech set data"
)

RESULTS_DIR = "/content/Results"

os.makedirs(
    RESULTS_DIR,
    exist_ok=True
)

# ============================================================
# LABELS
# ============================================================

emotion_map = {
    "angry": 0,
    "disgust": 1,
    "fear": 2,
    "happy": 3,
    "neutral": 4,
    "pleasant_surprise": 5,
    "sad": 6
}

idx_to_emotion = {
    v: k for k, v in emotion_map.items()
}

NUM_CLASSES = len(
    emotion_map
)

print(emotion_map)

# ============================================================
# DATASET DISCOVERY
# ============================================================

def normalize_emotion_name(folder_name):

    folder_name = folder_name.lower()

    if "pleasant" in folder_name:
        return "pleasant_surprise"

    if "fear" in folder_name:
        return "fear"

    if "sad" in folder_name:
        return "sad"

    if "angry" in folder_name:
        return "angry"

    if "happy" in folder_name:
        return "happy"

    if "neutral" in folder_name:
        return "neutral"

    if "disgust" in folder_name:
        return "disgust"

    raise ValueError(
        f"Unknown folder: {folder_name}"
    )


def extract_word(filename):

    filename = filename.replace(
        ".wav",
        ""
    )

    parts = filename.split("_")

    return parts[1]


def build_dataset():

    data = []

    for root, dirs, files in os.walk(
        DATASET_PATH
    ):

        for file in files:

            if not file.endswith(".wav"):
                continue

            emotion = normalize_emotion_name(
                os.path.basename(root)
            )

            label = emotion_map[
                emotion
            ]

            word = extract_word(
                file
            )

            data.append(
                {
                    "text": word,
                    "emotion": emotion,
                    "label": label
                }
            )

    return pd.DataFrame(data)


df = build_dataset()

print(
    "Dataset Size:",
    len(df)
)

print(
    df.head()
)

# ============================================================
# TRAIN / VALIDATION / TEST
# ============================================================

train_df, temp_df = train_test_split(
    df,
    test_size=0.30,
    stratify=df["label"],
    random_state=SEED
)

val_df, test_df = train_test_split(
    temp_df,
    test_size=0.50,
    stratify=temp_df["label"],
    random_state=SEED
)

print("Train:", len(train_df))
print("Validation:", len(val_df))
print("Test:", len(test_df))

# ============================================================
# TOKENIZER
# ============================================================

tokenizer = BertTokenizer.from_pretrained(
    "bert-base-uncased"
)

print("Tokenizer Loaded")

# ============================================================
# DATASET CLASS
# ============================================================

MAX_LEN = 16

class TESSTextDataset(Dataset):

    def __init__(self, dataframe):

        self.df = dataframe.reset_index(
            drop=True
        )

    def __len__(self):

        return len(self.df)

    def __getitem__(self, idx):

        row = self.df.iloc[idx]

        text = row["text"]

        label = row["label"]

        encoding = tokenizer(
            text,
            add_special_tokens=True,
            max_length=MAX_LEN,
            padding="max_length",
            truncation=True,
            return_attention_mask=True,
            return_tensors="pt"
        )

        return {
            "input_ids":
                encoding["input_ids"]
                .flatten(),

            "attention_mask":
                encoding["attention_mask"]
                .flatten(),

            "label":
                torch.tensor(
                    label,
                    dtype=torch.long
                )
        }

# ============================================================
# BERT CLASSIFIER
# ============================================================

class BERTEmotionClassifier(nn.Module):

    def __init__(
        self,
        dropout=0.3,
        num_classes=7
    ):

        super().__init__()

        self.bert = BertModel.from_pretrained(
            "bert-base-uncased"
        )

        self.fc1 = nn.Linear(
            768,
            256
        )

        self.relu = nn.ReLU()

        self.dropout = nn.Dropout(
            dropout
        )

        self.fc2 = nn.Linear(
            256,
            num_classes
        )

    def forward(
        self,
        input_ids,
        attention_mask
    ):

        outputs = self.bert(
            input_ids=input_ids,
            attention_mask=attention_mask
        )

        cls_embedding = (
            outputs.last_hidden_state[:, 0, :]
        )

        x = self.fc1(
            cls_embedding
        )

        x = self.relu(
            x
        )

        x = self.dropout(
            x
        )

        logits = self.fc2(
            x
        )

        return (
            logits,
            cls_embedding
        )

# ============================================================
# DATASETS
# ============================================================

train_dataset = TESSTextDataset(
    train_df
)

val_dataset = TESSTextDataset(
    val_df
)

test_dataset = TESSTextDataset(
    test_df
)

# ============================================================
# DATALOADERS
# ============================================================

BATCH_SIZE = 16

train_loader = DataLoader(
    train_dataset,
    batch_size=BATCH_SIZE,
    shuffle=True
)

val_loader = DataLoader(
    val_dataset,
    batch_size=BATCH_SIZE,
    shuffle=False
)

test_loader = DataLoader(
    test_dataset,
    batch_size=BATCH_SIZE,
    shuffle=False
)

print("DataLoaders Ready")

sample = next(
    iter(train_loader)
)

print(
    sample["input_ids"].shape
)

print(
    sample["attention_mask"].shape
)

print(
    sample["label"].shape
)

# ============================================================
# GRID SEARCH CONFIG
# ============================================================

learning_rates = [
    2e-5,
    5e-5
]

dropouts = [
    0.3,
    0.5
]

# ============================================================
# TRAINING CONFIG
# ============================================================

NUM_EPOCHS = 5

PATIENCE = 3

criterion = nn.CrossEntropyLoss()

print("Training Config Ready")

# ============================================================
# TRAIN FUNCTION
# ============================================================

def train_one_epoch(
    model,
    loader,
    optimizer
):

    model.train()

    running_loss = 0

    all_preds = []
    all_labels = []

    for batch in tqdm(loader):

        input_ids = batch[
            "input_ids"
        ].to(DEVICE)

        attention_mask = batch[
            "attention_mask"
        ].to(DEVICE)

        labels = batch[
            "label"
        ].to(DEVICE)

        optimizer.zero_grad()

        logits, _ = model(
            input_ids,
            attention_mask
        )

        loss = criterion(
            logits,
            labels
        )

        loss.backward()

        optimizer.step()

        running_loss += loss.item()

        preds = torch.argmax(
            logits,
            dim=1
        )

        all_preds.extend(
            preds.cpu().numpy()
        )

        all_labels.extend(
            labels.cpu().numpy()
        )

    epoch_loss = (
        running_loss /
        len(loader)
    )

    epoch_acc = accuracy_score(
        all_labels,
        all_preds
    )

    return (
        epoch_loss,
        epoch_acc
    )

# ============================================================
# VALIDATION
# ============================================================

def validate(
    model,
    loader
):

    model.eval()

    running_loss = 0

    all_preds = []
    all_labels = []

    with torch.no_grad():

        for batch in loader:

            input_ids = batch[
                "input_ids"
            ].to(DEVICE)

            attention_mask = batch[
                "attention_mask"
            ].to(DEVICE)

            labels = batch[
                "label"
            ].to(DEVICE)

            logits, _ = model(
                input_ids,
                attention_mask
            )

            loss = criterion(
                logits,
                labels
            )

            running_loss += loss.item()

            preds = torch.argmax(
                logits,
                dim=1
            )

            all_preds.extend(
                preds.cpu().numpy()
            )

            all_labels.extend(
                labels.cpu().numpy()
            )

    val_loss = (
        running_loss /
        len(loader)
    )

    val_acc = accuracy_score(
        all_labels,
        all_preds
    )

    return (
        val_loss,
        val_acc
    )

# ============================================================
# GRID SEARCH TRAINING
# ============================================================

best_val_acc = 0.0

best_config = None

best_model_path = os.path.join(
    RESULTS_DIR,
    "text_model.pth"
)

for lr in learning_rates:

    for dropout in dropouts:

        print("\n" + "=" * 60)

        print(
            f"LR={lr} | "
            f"Dropout={dropout}"
        )

        print("=" * 60)

        model = BERTEmotionClassifier(
            dropout=dropout,
            num_classes=NUM_CLASSES
        ).to(DEVICE)

        optimizer = torch.optim.AdamW(
            model.parameters(),
            lr=lr
        )

        patience_counter = 0

        best_epoch_acc = 0

        for epoch in range(
            NUM_EPOCHS
        ):

            train_loss, train_acc = (
                train_one_epoch(
                    model,
                    train_loader,
                    optimizer
                )
            )

            val_loss, val_acc = (
                validate(
                    model,
                    val_loader
                )
            )

            print(
                f"Epoch {epoch+1}/{NUM_EPOCHS} | "
                f"Train Acc={train_acc:.4f} | "
                f"Val Acc={val_acc:.4f}"
            )

            if val_acc > best_epoch_acc:

                best_epoch_acc = val_acc

                patience_counter = 0

            else:

                patience_counter += 1

            if val_acc > best_val_acc:

                best_val_acc = val_acc

                best_config = {
                    "learning_rate": lr,
                    "dropout": dropout
                }

                torch.save(
                    model.state_dict(),
                    best_model_path
                )

            if patience_counter >= PATIENCE:

                print(
                    "Early Stopping Triggered"
                )

                break

print("\nBest Validation Accuracy:")
print(best_val_acc)

print("\nBest Config:")
print(best_config)

config_path = os.path.join(
    RESULTS_DIR,
    "text_best_config.json"
)

with open(
    config_path,
    "w"
) as f:

    json.dump(
        best_config,
        f,
        indent=4
    )

print("Best Config Saved")

best_model = BERTEmotionClassifier(
    dropout=best_config["dropout"],
    num_classes=NUM_CLASSES
)

best_model.load_state_dict(
    torch.load(
        best_model_path,
        map_location=DEVICE
    )
)

best_model = best_model.to(
    DEVICE
)

best_model.eval()

print("Best Model Loaded")

# ============================================================
# TEST EVALUATION
# ============================================================

all_preds = []
all_labels = []

all_embeddings = []

with torch.no_grad():

    for batch in tqdm(
        test_loader
    ):

        input_ids = batch[
            "input_ids"
        ].to(DEVICE)

        attention_mask = batch[
            "attention_mask"
        ].to(DEVICE)

        labels = batch[
            "label"
        ].to(DEVICE)

        logits, embeddings = best_model(
            input_ids,
            attention_mask
        )

        preds = torch.argmax(
            logits,
            dim=1
        )

        all_preds.extend(
            preds.cpu().numpy()
        )

        all_labels.extend(
            labels.cpu().numpy()
        )

        all_embeddings.extend(
            embeddings.cpu().numpy()
        )

test_acc = accuracy_score(
    all_labels,
    all_preds
)

test_precision = precision_score(
    all_labels,
    all_preds,
    average="weighted",
    zero_division=0
)

test_recall = recall_score(
    all_labels,
    all_preds,
    average="weighted",
    zero_division=0
)

test_f1 = f1_score(
    all_labels,
    all_preds,
    average="weighted",
    zero_division=0
)

print("\nTest Accuracy:", test_acc)
print("Test Precision:", test_precision)
print("Test Recall:", test_recall)
print("Test F1:", test_f1)

# ============================================================
# CLASSIFICATION REPORT
# ============================================================

report = classification_report(
    all_labels,
    all_preds,
    target_names=[
        idx_to_emotion[i]
        for i in range(NUM_CLASSES)
    ],
    zero_division=0
)

print(report)

report_path = os.path.join(
    RESULTS_DIR,
    "text_classification_report.txt"
)

with open(
    report_path,
    "w"
) as f:

    f.write(report)

print("Classification Report Saved")

# ============================================================
# CONFUSION MATRIX
# ============================================================

cm = confusion_matrix(
    all_labels,
    all_preds
)

plt.figure(figsize=(10,8))

sns.heatmap(
    cm,
    annot=True,
    fmt="d",
    cmap="Blues",
    xticklabels=list(emotion_map.keys()),
    yticklabels=list(emotion_map.keys())
)

plt.title(
    "Text Emotion Confusion Matrix"
)

plt.xlabel(
    "Predicted"
)

plt.ylabel(
    "Actual"
)

cm_path = os.path.join(
    RESULTS_DIR,
    "text_confusion_matrix.png"
)

plt.savefig(
    cm_path,
    bbox_inches="tight"
)

plt.show()

print("Confusion Matrix Saved")

# ============================================================
# ACCURACY TABLE
# ============================================================

results_df = pd.DataFrame(
    {
        "Metric": [
            "Accuracy",
            "Precision",
            "Recall",
            "F1 Score"
        ],
        "Value": [
            test_acc,
            test_precision,
            test_recall,
            test_f1
        ]
    }
)

csv_path = os.path.join(
    RESULTS_DIR,
    "text_accuracy.csv"
)

results_df.to_csv(
    csv_path,
    index=False
)

print(results_df)

print("Accuracy Table Saved")

# ============================================================
# TSNE VISUALIZATION
# ============================================================

embeddings_np = np.array(
    all_embeddings
)

labels_np = np.array(
    all_labels
)

tsne = TSNE(
    n_components=2,
    random_state=42,
    perplexity=30
)

tsne_features = tsne.fit_transform(
    embeddings_np
)

plt.figure(figsize=(10,8))

scatter = plt.scatter(
    tsne_features[:,0],
    tsne_features[:,1],
    c=labels_np,
    cmap="tab10"
)

plt.colorbar(scatter)

plt.title(
    "t-SNE of Text Embeddings"
)

tsne_path = os.path.join(
    RESULTS_DIR,
    "text_tsne.png"
)

plt.savefig(
    tsne_path,
    bbox_inches="tight"
)

plt.show()

print("t-SNE Saved")

# ============================================================
# VERIFY OUTPUTS
# ============================================================

print(
    os.listdir(
        RESULTS_DIR
    )
)

