# -*- coding: utf-8 -*-
"""speech_train.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1K48pvUZIAflf5Ywb0S5lX2r8dyJNIXik
"""

from google.colab import drive
drive.mount('/content/drive')

!unzip -q \
"/content/drive/MyDrive/Emotion_Project/datasets/tess.zip" \
-d "/content/drive/MyDrive/Emotion_Project/datasets/"

!find "/content/drive/MyDrive/Emotion_Project/datasets" -name "*.wav" | head

!find "/content/drive/MyDrive/Emotion_Project/datasets" -type d | head -20

import os

wav_files = []

for root, dirs, files in os.walk("/content/drive/MyDrive/Emotion_Project/datasets/TESS Toronto emotional speech set data"):
    for f in files:
        if f.endswith(".wav"):
            wav_files.append(os.path.join(root, f))

print("Total wav files:", len(wav_files))

for f in wav_files[:10]:
    print(os.path.basename(f))

DATASET_PATH = "/content/drive/MyDrive/Emotion_Project/datasets/TESS Toronto emotional speech set data"

# ============================================================
# INSTALL REQUIRED PACKAGES
# ============================================================

!pip install -q transformers==4.41.2
!pip install -q librosa soundfile
!pip install -q scikit-learn seaborn tqdm

import os
os.kill(os.getpid(), 9)

# ============================================================
# IMPORTS
# ============================================================

import os
import json
import random
import warnings

import numpy as np
import pandas as pd

from tqdm import tqdm

import librosa
import soundfile as sf

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split

from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix,
    precision_score,
    recall_score,
    f1_score
)

from sklearn.manifold import TSNE

import torch
import torch.nn as nn

from torch.utils.data import (
    Dataset,
    DataLoader
)

# ============================================================
# HUGGING FACE
# ============================================================

from transformers import (
    HubertModel,
    AutoFeatureExtractor
)

warnings.filterwarnings("ignore")

# ============================================================
# RANDOM SEED
# ============================================================

SEED = 42

random.seed(SEED)
np.random.seed(SEED)

torch.manual_seed(SEED)

if torch.cuda.is_available():
    torch.cuda.manual_seed_all(SEED)

# ============================================================
# DEVICE
# ============================================================

DEVICE = torch.device(
    "cuda" if torch.cuda.is_available() else "cpu"
)

print("Device:", DEVICE)

# ============================================================
# LOAD HUBERT FEATURE EXTRACTOR
# ============================================================

print("Loading HuBERT Feature Extractor...")

feature_extractor = AutoFeatureExtractor.from_pretrained(
    "facebook/hubert-base-ls960"
)

print("Loading HuBERT Model...")

hubert = HubertModel.from_pretrained(
    "facebook/hubert-base-ls960"
)

hubert = hubert.to(DEVICE)

print("HuBERT Loaded Successfully")
print("Hidden Size:", hubert.config.hidden_size)

# ============================================================
# FREEZE HUBERT (OPTION A)
# ============================================================

for param in hubert.parameters():
    param.requires_grad = False

print("HuBERT frozen successfully.")

# ============================================================
# PATHS
# ============================================================

DATASET_PATH = (
    "/content/drive/MyDrive/Emotion_Project/datasets/"
    "TESS Toronto emotional speech set data"
)

RESULTS_DIR = "/content/Results"

os.makedirs(
    RESULTS_DIR,
    exist_ok=True
)

# ============================================================
# LABELS
# ============================================================

emotion_map = {
    "angry": 0,
    "disgust": 1,
    "fear": 2,
    "happy": 3,
    "neutral": 4,
    "pleasant_surprise": 5,
    "sad": 6
}

idx_to_emotion = {
    v: k for k, v in emotion_map.items()
}

NUM_CLASSES = len(
    emotion_map
)

print("Classes:")
print(emotion_map)

# ============================================================
# DATASET DISCOVERY
# ============================================================

def normalize_emotion_name(folder_name):

    folder_name = folder_name.lower()

    if "pleasant" in folder_name:
        return "pleasant_surprise"

    if "fear" in folder_name:
        return "fear"

    if "sad" in folder_name:
        return "sad"

    if "angry" in folder_name:
        return "angry"

    if "happy" in folder_name:
        return "happy"

    if "neutral" in folder_name:
        return "neutral"

    if "disgust" in folder_name:
        return "disgust"

    raise ValueError(
        f"Unknown folder: {folder_name}"
    )


def build_dataset():

    data = []

    for root, dirs, files in os.walk(
        DATASET_PATH
    ):

        for file in files:

            if not file.endswith(".wav"):
                continue

            file_path = os.path.join(
                root,
                file
            )

            emotion = normalize_emotion_name(
                os.path.basename(root)
            )

            label = emotion_map[
                emotion
            ]

            data.append(
                {
                    "path": file_path,
                    "emotion": emotion,
                    "label": label
                }
            )

    return pd.DataFrame(data)


df = build_dataset()

print(
    "Dataset Size:",
    len(df)
)

print(
    df["emotion"].value_counts()
)

# ============================================================
# TRAIN / VALIDATION / TEST SPLIT
# ============================================================

train_df, temp_df = train_test_split(
    df,
    test_size=0.30,
    stratify=df["label"],
    random_state=SEED
)

val_df, test_df = train_test_split(
    temp_df,
    test_size=0.50,
    stratify=temp_df["label"],
    random_state=SEED
)

print("Train:", len(train_df))
print("Validation:", len(val_df))
print("Test:", len(test_df))

# ============================================================
# AUDIO PREPROCESSING
# ============================================================

TARGET_SR = 16000
MAX_AUDIO_LENGTH = 4
MAX_AUDIO_SAMPLES = TARGET_SR * MAX_AUDIO_LENGTH


def preprocess_audio(audio_path):

    signal, sr = librosa.load(
        audio_path,
        sr=TARGET_SR
    )

    signal, _ = librosa.effects.trim(
        signal,
        top_db=20
    )

    signal = librosa.util.normalize(
        signal
    )

    if len(signal) > MAX_AUDIO_SAMPLES:

        signal = signal[:MAX_AUDIO_SAMPLES]

    else:

        padding = (
            MAX_AUDIO_SAMPLES
            - len(signal)
        )

        signal = np.pad(
            signal,
            (0, padding),
            mode="constant"
        )

    return signal.astype(
        np.float32
    )


# ============================================================
# DATASET
# ============================================================

class TESSSpeechDataset(Dataset):

    def __init__(self, dataframe):

        self.df = dataframe.reset_index(
            drop=True
        )

    def __len__(self):

        return len(self.df)

    def __getitem__(self, idx):

        row = self.df.iloc[idx]

        audio = preprocess_audio(
            row["path"]
        )

        label = row["label"]

        return (
            torch.tensor(
                audio,
                dtype=torch.float32
            ),
            label
        )


# ============================================================
# FEATURE EXTRACTOR
# ============================================================

feature_extractor = AutoFeatureExtractor.from_pretrained(
    "facebook/hubert-base-ls960"
)


# ============================================================
# COLLATE FUNCTION
# ============================================================

def collate_fn(batch):

    audios = []
    labels = []

    for audio, label in batch:

        audios.append(
            audio.numpy()
        )

        labels.append(
            label
        )

    processed = feature_extractor(
        audios,
        sampling_rate=16000,
        return_tensors="pt",
        padding=True
    )

    input_values = processed[
        "input_values"
    ]

    labels = torch.tensor(
        labels,
        dtype=torch.long
    )

    return (
        input_values,
        labels
    )


# ============================================================
# MODEL
# ============================================================

class HuBERTBiLSTM(nn.Module):

    def __init__(
        self,
        hidden_size=128,
        dropout=0.3,
        num_classes=7
    ):

        super().__init__()

        self.hubert = HubertModel.from_pretrained(
            "facebook/hubert-base-ls960"
        )

        for param in self.hubert.parameters():
            param.requires_grad = False

        self.bilstm = nn.LSTM(
            input_size=768,
            hidden_size=hidden_size,
            num_layers=2,
            batch_first=True,
            bidirectional=True,
            dropout=dropout
        )

        self.fc1 = nn.Linear(
            hidden_size * 2,
            256
        )

        self.relu = nn.ReLU()

        self.dropout = nn.Dropout(
            dropout
        )

        self.fc2 = nn.Linear(
            256,
            num_classes
        )

    def forward(
        self,
        input_values
    ):

        with torch.no_grad():

            hubert_output = self.hubert(
                input_values=input_values
            )

            features = (
                hubert_output
                .last_hidden_state
            )

        lstm_out, _ = self.bilstm(
            features
        )

        embedding = lstm_out[:, -1, :]

        x = self.fc1(
            embedding
        )

        x = self.relu(
            x
        )

        x = self.dropout(
            x
        )

        logits = self.fc2(
            x
        )

        return (
            logits,
            embedding
        )


# ============================================================
# DATASETS
# ============================================================

train_dataset = TESSSpeechDataset(
    train_df
)

val_dataset = TESSSpeechDataset(
    val_df
)

test_dataset = TESSSpeechDataset(
    test_df
)


# ============================================================
# DATALOADERS
# ============================================================

BATCH_SIZE = 8

train_loader = DataLoader(
    train_dataset,
    batch_size=BATCH_SIZE,
    shuffle=True,
    collate_fn=collate_fn
)

val_loader = DataLoader(
    val_dataset,
    batch_size=BATCH_SIZE,
    shuffle=False,
    collate_fn=collate_fn
)

test_loader = DataLoader(
    test_dataset,
    batch_size=BATCH_SIZE,
    shuffle=False,
    collate_fn=collate_fn
)

print("DataLoaders Ready")

input_values, labels = next(
    iter(train_loader)
)

print(input_values.shape)
print(labels.shape)

# ============================================================
# GRID SEARCH CONFIG
# ============================================================

learning_rates = [
    1e-4,
    5e-5
]

dropouts = [
    0.3,
    0.5
]

hidden_sizes = [
    128,
    256
]

# ============================================================
# TRAINING CONFIG
# ============================================================

NUM_EPOCHS = 5

PATIENCE = 5

criterion = nn.CrossEntropyLoss()

print("Training Config Ready")

# ============================================================
# TRAIN FUNCTION
# ============================================================

def train_one_epoch(
    model,
    loader,
    optimizer
):

    model.train()

    running_loss = 0.0

    all_preds = []
    all_labels = []

    for input_values, labels in tqdm(loader):

        input_values = input_values.to(
            DEVICE
        )

        labels = labels.to(
            DEVICE
        )

        optimizer.zero_grad()

        logits, _ = model(
            input_values
        )

        loss = criterion(
            logits,
            labels
        )

        loss.backward()

        optimizer.step()

        running_loss += loss.item()

        preds = torch.argmax(
            logits,
            dim=1
        )

        all_preds.extend(
            preds.cpu().numpy()
        )

        all_labels.extend(
            labels.cpu().numpy()
        )

    epoch_loss = (
        running_loss /
        len(loader)
    )

    epoch_acc = accuracy_score(
        all_labels,
        all_preds
    )

    return (
        epoch_loss,
        epoch_acc
    )

# ============================================================
# VALIDATION
# ============================================================

def validate(
    model,
    loader
):

    model.eval()

    running_loss = 0.0

    all_preds = []
    all_labels = []

    with torch.no_grad():

        for input_values, labels in loader:

            input_values = input_values.to(
                DEVICE
            )

            labels = labels.to(
                DEVICE
            )

            logits, _ = model(
                input_values
            )

            loss = criterion(
                logits,
                labels
            )

            running_loss += loss.item()

            preds = torch.argmax(
                logits,
                dim=1
            )

            all_preds.extend(
                preds.cpu().numpy()
            )

            all_labels.extend(
                labels.cpu().numpy()
            )

    val_loss = (
        running_loss /
        len(loader)
    )

    val_acc = accuracy_score(
        all_labels,
        all_preds
    )

    return (
        val_loss,
        val_acc
    )

# ============================================================
# GRID SEARCH TRAINING
# ============================================================

best_val_acc = 0.0

best_config = None

best_model_path = os.path.join(
    RESULTS_DIR,
    "speech_model.pth"
)

history = []

for lr in learning_rates:

    for dropout in dropouts:

        for hidden_size in hidden_sizes:

            print("\n" + "=" * 60)
            print(
                f"LR={lr} | "
                f"Dropout={dropout} | "
                f"Hidden={hidden_size}"
            )
            print("=" * 60)

            model = HuBERTBiLSTM(
                hidden_size=hidden_size,
                dropout=dropout,
                num_classes=NUM_CLASSES
            ).to(DEVICE)

            optimizer = torch.optim.AdamW(
                model.parameters(),
                lr=lr
            )

            best_epoch_acc = 0.0
            patience_counter = 0

            train_losses = []
            val_losses = []

            train_accs = []
            val_accs = []

            for epoch in range(NUM_EPOCHS):

                train_loss, train_acc = train_one_epoch(
                    model,
                    train_loader,
                    optimizer
                )

                val_loss, val_acc = validate(
                    model,
                    val_loader
                )

                train_losses.append(
                    train_loss
                )

                val_losses.append(
                    val_loss
                )

                train_accs.append(
                    train_acc
                )

                val_accs.append(
                    val_acc
                )

                print(
                    f"Epoch {epoch+1}/{NUM_EPOCHS} | "
                    f"Train Acc={train_acc:.4f} | "
                    f"Val Acc={val_acc:.4f}"
                )

                if val_acc > best_epoch_acc:

                    best_epoch_acc = val_acc

                    patience_counter = 0

                else:

                    patience_counter += 1

                if val_acc > best_val_acc:

                    best_val_acc = val_acc

                    best_config = {
                        "learning_rate": lr,
                        "dropout": dropout,
                        "hidden_size": hidden_size
                    }

                    torch.save(
                        model.state_dict(),
                        best_model_path
                    )

                if patience_counter >= PATIENCE:

                    print(
                        "Early Stopping Triggered"
                    )

                    break

            history.append(
                {
                    "lr": lr,
                    "dropout": dropout,
                    "hidden_size": hidden_size,
                    "best_val_acc": best_epoch_acc
                }
            )

print("\nBest Validation Accuracy:")
print(best_val_acc)

print("\nBest Configuration:")
print(best_config)

config_path = os.path.join(
    RESULTS_DIR,
    "speech_best_config.json"
)

with open(
    config_path,
    "w"
) as f:

    json.dump(
        best_config,
        f,
        indent=4
    )

print("Best Config Saved")

best_model = HuBERTBiLSTM(
    hidden_size=best_config["hidden_size"],
    dropout=best_config["dropout"],
    num_classes=NUM_CLASSES
)

best_model.load_state_dict(
    torch.load(
        best_model_path,
        map_location=DEVICE
    )
)

best_model = best_model.to(
    DEVICE
)

best_model.eval()

print("Best Model Loaded")

all_preds = []
all_labels = []

all_embeddings = []

with torch.no_grad():

    for input_values, labels in tqdm(
        test_loader
    ):

        input_values = input_values.to(
            DEVICE
        )

        labels = labels.to(
            DEVICE
        )

        logits, embeddings = best_model(
            input_values
        )

        preds = torch.argmax(
            logits,
            dim=1
        )

        all_preds.extend(
            preds.cpu().numpy()
        )

        all_labels.extend(
            labels.cpu().numpy()
        )

        all_embeddings.extend(
            embeddings.cpu().numpy()
        )

test_acc = accuracy_score(
    all_labels,
    all_preds
)

test_precision = precision_score(
    all_labels,
    all_preds,
    average="weighted"
)

test_recall = recall_score(
    all_labels,
    all_preds,
    average="weighted"
)

test_f1 = f1_score(
    all_labels,
    all_preds,
    average="weighted"
)

print("\nTest Accuracy:", test_acc)
print("Test Precision:", test_precision)
print("Test Recall:", test_recall)
print("Test F1:", test_f1)

# ============================================================
# CLASSIFICATION REPORT
# ============================================================

report = classification_report(
    all_labels,
    all_preds,
    target_names=[
        idx_to_emotion[i]
        for i in range(NUM_CLASSES)
    ]
)

print(report)

report_path = os.path.join(
    RESULTS_DIR,
    "speech_classification_report.txt"
)

with open(
    report_path,
    "w"
) as f:

    f.write(report)

print("Classification Report Saved")

# ============================================================
# CONFUSION MATRIX
# ============================================================

cm = confusion_matrix(
    all_labels,
    all_preds
)

plt.figure(figsize=(10, 8))

sns.heatmap(
    cm,
    annot=True,
    fmt="d",
    cmap="Blues",
    xticklabels=list(
        emotion_map.keys()
    ),
    yticklabels=list(
        emotion_map.keys()
    )
)

plt.title(
    "Speech Emotion Confusion Matrix"
)

plt.xlabel(
    "Predicted"
)

plt.ylabel(
    "Actual"
)

cm_path = os.path.join(
    RESULTS_DIR,
    "speech_confusion_matrix.png"
)

plt.savefig(
    cm_path,
    bbox_inches="tight"
)

plt.show()

print("Confusion Matrix Saved")

# ============================================================
# ACCURACY TABLE
# ============================================================

results_df = pd.DataFrame(
    {
        "Metric": [
            "Accuracy",
            "Precision",
            "Recall",
            "F1 Score"
        ],
        "Value": [
            test_acc,
            test_precision,
            test_recall,
            test_f1
        ]
    }
)

csv_path = os.path.join(
    RESULTS_DIR,
    "speech_accuracy.csv"
)

results_df.to_csv(
    csv_path,
    index=False
)

print(results_df)

print("Accuracy Table Saved")

# ============================================================
# TSNE VISUALIZATION
# ============================================================

embeddings_np = np.array(
    all_embeddings
)

labels_np = np.array(
    all_labels
)

tsne = TSNE(
    n_components=2,
    random_state=42,
    perplexity=30
)

tsne_features = tsne.fit_transform(
    embeddings_np
)

plt.figure(figsize=(10, 8))

scatter = plt.scatter(
    tsne_features[:, 0],
    tsne_features[:, 1],
    c=labels_np,
    cmap="tab10"
)

plt.colorbar(scatter)

plt.title(
    "t-SNE of Speech Embeddings"
)

tsne_path = os.path.join(
    RESULTS_DIR,
    "speech_tsne.png"
)

plt.savefig(
    tsne_path,
    bbox_inches="tight"
)

plt.show()

print("t-SNE Saved")

