# -*- coding: utf-8 -*-
"""fusion_train.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1krkd_061mob5UiVT4ugQcJLG_JoX7xLJ
"""

from google.colab import drive
drive.mount('/content/drive')

import os

print(
    os.path.exists(
        "/content/drive/MyDrive/Emotion_Project/datasets"
    )
)

# ============================================================
# INSTALL REQUIRED PACKAGES
# ============================================================

!pip install -q transformers==4.41.2
!pip install -q librosa soundfile
!pip install -q scikit-learn seaborn tqdm

# ============================================================
# IMPORTS
# ============================================================

import os
import json
import random
import warnings

import numpy as np
import pandas as pd

from tqdm import tqdm

import librosa

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split

from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix,
    precision_score,
    recall_score,
    f1_score
)

from sklearn.manifold import TSNE

import torch
import torch.nn as nn

from torch.utils.data import (
    Dataset,
    DataLoader
)

from transformers import (
    HubertModel,
    AutoFeatureExtractor,
    BertTokenizer,
    BertModel
)

warnings.filterwarnings("ignore")

# ============================================================
# RANDOM SEED
# ============================================================

SEED = 42

random.seed(SEED)
np.random.seed(SEED)

torch.manual_seed(SEED)

if torch.cuda.is_available():
    torch.cuda.manual_seed_all(SEED)

# ============================================================
# DEVICE
# ============================================================

DEVICE = torch.device(
    "cuda" if torch.cuda.is_available() else "cpu"
)

print("Device:", DEVICE)

# ============================================================
# DATASET PATH
# ============================================================

DATASET_PATH = (
    "/content/drive/MyDrive/Emotion_Project/datasets/"
    "TESS Toronto emotional speech set data"
)

# ============================================================
# PRETRAINED MODELS
# ============================================================

SPEECH_MODEL_PATH = (
    "/content/speech_model.pth"
)

TEXT_MODEL_PATH = (
    "/content/text_model.pth"
)

# ============================================================
# RESULTS
# ============================================================

RESULTS_DIR = "/content/Results"

os.makedirs(
    RESULTS_DIR,
    exist_ok=True
)

print("Paths Ready")

# ============================================================
# LABELS
# ============================================================

emotion_map = {
    "angry": 0,
    "disgust": 1,
    "fear": 2,
    "happy": 3,
    "neutral": 4,
    "pleasant_surprise": 5,
    "sad": 6
}

idx_to_emotion = {
    v: k
    for k, v in emotion_map.items()
}

NUM_CLASSES = len(
    emotion_map
)

print(emotion_map)

# ============================================================
# DATASET DISCOVERY
# ============================================================

def normalize_emotion_name(folder_name):

    folder_name = folder_name.lower()

    if "pleasant" in folder_name:
        return "pleasant_surprise"

    if "fear" in folder_name:
        return "fear"

    if "sad" in folder_name:
        return "sad"

    if "angry" in folder_name:
        return "angry"

    if "happy" in folder_name:
        return "happy"

    if "neutral" in folder_name:
        return "neutral"

    if "disgust" in folder_name:
        return "disgust"

    raise ValueError(
        f"Unknown folder {folder_name}"
    )


def extract_word(filename):

    filename = filename.replace(
        ".wav",
        ""
    )

    parts = filename.split("_")

    return parts[1]


data = []

for root, dirs, files in os.walk(
    DATASET_PATH
):

    for file in files:

        if not file.endswith(".wav"):
            continue

        emotion = normalize_emotion_name(
            os.path.basename(root)
        )

        label = emotion_map[
            emotion
        ]

        text = extract_word(
            file
        )

        data.append(
            [
                os.path.join(
                    root,
                    file
                ),
                text,
                label
            ]
        )

df = pd.DataFrame(
    data,
    columns=[
        "audio_path",
        "text",
        "label"
    ]
)

print(
    "Dataset Size:",
    len(df)
)

df.head()

import os

print(os.path.exists(
    "/content/drive/MyDrive/Emotion_Project/datasets"
))

print(os.listdir(
    "/content/drive/MyDrive/Emotion_Project/datasets"
))

# ============================================================
# SPLIT
# ============================================================

train_df, temp_df = train_test_split(
    df,
    test_size=0.30,
    stratify=df["label"],
    random_state=42
)

val_df, test_df = train_test_split(
    temp_df,
    test_size=0.50,
    stratify=temp_df["label"],
    random_state=42
)

print("Train:", len(train_df))
print("Validation:", len(val_df))
print("Test:", len(test_df))

# ============================================================
# LOAD FEATURE EXTRACTOR
# ============================================================

feature_extractor = AutoFeatureExtractor.from_pretrained(
    "facebook/hubert-base-ls960"
)

# ============================================================
# LOAD TOKENIZER
# ============================================================

tokenizer = BertTokenizer.from_pretrained(
    "bert-base-uncased"
)

print("Feature Extractor Loaded")
print("Tokenizer Loaded")

# ============================================================
# AUDIO PREPROCESSING
# ============================================================

TARGET_SR = 16000
MAX_AUDIO_LENGTH = 4 * TARGET_SR

def preprocess_audio(audio_path):

    signal, sr = librosa.load(
        audio_path,
        sr=TARGET_SR
    )

    signal, _ = librosa.effects.trim(
        signal
    )

    signal = librosa.util.normalize(
        signal
    )

    if len(signal) > MAX_AUDIO_LENGTH:

        signal = signal[
            :MAX_AUDIO_LENGTH
        ]

    else:

        padding = (
            MAX_AUDIO_LENGTH
            - len(signal)
        )

        signal = np.pad(
            signal,
            (0, padding)
        )

    return signal.astype(
        np.float32
    )

# ============================================================
# FUSION DATASET
# ============================================================

MAX_LEN = 16

class FusionDataset(Dataset):

    def __init__(self, dataframe):

        self.df = dataframe.reset_index(
            drop=True
        )

    def __len__(self):

        return len(self.df)

    def __getitem__(self, idx):

        row = self.df.iloc[idx]

        audio_path = row[
            "audio_path"
        ]

        text = row[
            "text"
        ]

        label = row[
            "label"
        ]

        # ====================================================
        # AUDIO
        # ====================================================

        audio = preprocess_audio(
            audio_path
        )

        # ====================================================
        # TEXT
        # ====================================================

        encoding = tokenizer(
            text,
            add_special_tokens=True,
            max_length=MAX_LEN,
            padding="max_length",
            truncation=True,
            return_attention_mask=True,
            return_tensors="pt"
        )

        return {
            "audio":
                torch.tensor(
                    audio,
                    dtype=torch.float
                ),

            "input_ids":
                encoding["input_ids"]
                .flatten(),

            "attention_mask":
                encoding["attention_mask"]
                .flatten(),

            "label":
                torch.tensor(
                    label,
                    dtype=torch.long
                )
        }

# ============================================================
# SPEECH MODEL
# ============================================================

class HuBERTBiLSTM(nn.Module):

    def __init__(
        self,
        hidden_size=256,
        dropout=0.3,
        num_classes=7
    ):

        super().__init__()

        self.hubert = HubertModel.from_pretrained(
            "facebook/hubert-base-ls960"
        )

        for param in self.hubert.parameters():
            param.requires_grad = False

        self.bilstm = nn.LSTM(
            input_size=768,
            hidden_size=hidden_size,
            num_layers=2,
            batch_first=True,
            bidirectional=True,
            dropout=dropout
        )

        self.fc1 = nn.Linear(
            hidden_size * 2,
            256
        )

        self.relu = nn.ReLU()

        self.dropout = nn.Dropout(
            dropout
        )

        self.fc2 = nn.Linear(
            256,
            num_classes
        )

    def forward(self, input_values):

        outputs = self.hubert(
            input_values
        )

        hidden_states = (
            outputs.last_hidden_state
        )

        lstm_out, _ = self.bilstm(
            hidden_states
        )

        embedding = torch.mean(
            lstm_out,
            dim=1
        )

        x = self.fc1(
            embedding
        )

        x = self.relu(x)

        x = self.dropout(x)

        logits = self.fc2(x)

        return logits, x

# ============================================================
# TEXT MODEL
# ============================================================

class BERTEmotionClassifier(nn.Module):

    def __init__(
        self,
        dropout=0.3,
        num_classes=7
    ):

        super().__init__()

        self.bert = BertModel.from_pretrained(
            "bert-base-uncased"
        )

        self.fc1 = nn.Linear(
            768,
            256
        )

        self.relu = nn.ReLU()

        self.dropout = nn.Dropout(
            dropout
        )

        self.fc2 = nn.Linear(
            256,
            num_classes
        )

    def forward(
        self,
        input_ids,
        attention_mask
    ):

        outputs = self.bert(
            input_ids=input_ids,
            attention_mask=attention_mask
        )

        cls_embedding = (
            outputs.last_hidden_state[:,0,:]
        )

        x = self.fc1(
            cls_embedding
        )

        x = self.relu(x)

        x = self.dropout(x)

        logits = self.fc2(x)

        return logits, cls_embedding

# ============================================================
# LOAD PRETRAINED SPEECH MODEL
# ============================================================

speech_model = HuBERTBiLSTM()

speech_model.load_state_dict(
    torch.load(
        SPEECH_MODEL_PATH,
        map_location=DEVICE
    )
)

speech_model = speech_model.to(
    DEVICE
)

speech_model.eval()

print("Speech Model Loaded")

# ============================================================
# LOAD PRETRAINED TEXT MODEL
# ============================================================

text_model = BERTEmotionClassifier()

text_model.load_state_dict(
    torch.load(
        TEXT_MODEL_PATH,
        map_location=DEVICE
    )
)

text_model = text_model.to(
    DEVICE
)

text_model.eval()

print("Text Model Loaded")

# ============================================================
# FUSION MODEL
# ============================================================

class FusionEmotionModel(nn.Module):

    def __init__(
        self,
        dropout=0.3,
        num_classes=7
    ):

        super().__init__()

        # Speech embedding = 256
        # Text embedding = 768

        self.fc1 = nn.Linear(
            1024,
            512
        )

        self.relu1 = nn.ReLU()

        self.dropout1 = nn.Dropout(
            dropout
        )

        self.fc2 = nn.Linear(
            512,
            256
        )

        self.relu2 = nn.ReLU()

        self.dropout2 = nn.Dropout(
            dropout
        )

        self.fc3 = nn.Linear(
            256,
            num_classes
        )

    def forward(
        self,
        speech_embedding,
        text_embedding
    ):

        fused = torch.cat(
            [
                speech_embedding,
                text_embedding
            ],
            dim=1
        )

        x = self.fc1(fused)

        x = self.relu1(x)

        x = self.dropout1(x)

        x = self.fc2(x)

        x = self.relu2(x)

        x = self.dropout2(x)

        logits = self.fc3(x)

        return logits

# ============================================================
# DATASETS
# ============================================================

train_dataset = FusionDataset(
    train_df
)

val_dataset = FusionDataset(
    val_df
)

test_dataset = FusionDataset(
    test_df
)

# ============================================================
# DATALOADERS
# ============================================================

BATCH_SIZE = 8

train_loader = DataLoader(
    train_dataset,
    batch_size=BATCH_SIZE,
    shuffle=True
)

val_loader = DataLoader(
    val_dataset,
    batch_size=BATCH_SIZE,
    shuffle=False
)

test_loader = DataLoader(
    test_dataset,
    batch_size=BATCH_SIZE,
    shuffle=False
)

print("Fusion DataLoaders Ready")

sample = next(
    iter(train_loader)
)

print(
    sample["audio"].shape
)

print(
    sample["input_ids"].shape
)

print(
    sample["attention_mask"].shape
)

print(
    sample["label"].shape
)

import os

print(
    "Speech Model Size (MB):",
    os.path.getsize(
        "/content/speech_model.pth"
    ) / (1024 * 1024)
)

print(
    "Text Model Size (MB):",
    os.path.getsize(
        "/content/text_model.pth"
    ) / (1024 * 1024)
)

import torch

try:
    checkpoint = torch.load(
        "/content/speech_model.pth",
        map_location="cpu"
    )

    print("Speech Model OK")
    print(type(checkpoint))

except Exception as e:
    print("Speech Model Error:")
    print(e)

print("-" * 50)

try:
    checkpoint = torch.load(
        "/content/text_model.pth",
        map_location="cpu"
    )

    print("Text Model OK")
    print(type(checkpoint))

except Exception as e:
    print("Text Model Error:")
    print(e)

speech_checkpoint = torch.load(
    "/content/speech_model.pth",
    map_location="cpu"
)

print(list(speech_checkpoint.keys())[:20])

text_checkpoint = torch.load(
    "/content/text_model.pth",
    map_location="cpu"
)

print(list(text_checkpoint.keys())[:20])

speech_checkpoint = torch.load(
    "/content/speech_model.pth",
    map_location="cpu"
)

print(
    speech_checkpoint["fc1.weight"].shape
)

print(
    speech_checkpoint["fc2.weight"].shape
)

text_checkpoint = torch.load(
    "/content/text_model.pth",
    map_location="cpu"
)

print(
    text_checkpoint["fc1.weight"].shape
)

print(
    text_checkpoint["fc2.weight"].shape
)

# ============================================================
# TRAINING CONFIG
# ============================================================

LEARNING_RATE = 1e-4

NUM_EPOCHS = 10

PATIENCE = 3

criterion = nn.CrossEntropyLoss()

print("Fusion Config Ready")

# ============================================================
# CREATE FUSION MODEL
# ============================================================

fusion_model = FusionEmotionModel(
    dropout=0.3,
    num_classes=NUM_CLASSES
).to(DEVICE)

optimizer = torch.optim.AdamW(
    fusion_model.parameters(),
    lr=LEARNING_RATE
)

print("Fusion Model Ready")

# ============================================================
# TRAIN FUNCTION
# ============================================================

def train_one_epoch():

    fusion_model.train()

    running_loss = 0

    all_preds = []
    all_labels = []

    for batch in tqdm(train_loader):

        audio = batch[
            "audio"
        ].to(DEVICE)

        input_ids = batch[
            "input_ids"
        ].to(DEVICE)

        attention_mask = batch[
            "attention_mask"
        ].to(DEVICE)

        labels = batch[
            "label"
        ].to(DEVICE)

        optimizer.zero_grad()

        with torch.no_grad():

            _, speech_embedding = speech_model(
                audio
            )

            _, text_embedding = text_model(
                input_ids,
                attention_mask
            )

        logits = fusion_model(
            speech_embedding,
            text_embedding
        )

        loss = criterion(
            logits,
            labels
        )

        loss.backward()

        optimizer.step()

        running_loss += loss.item()

        preds = torch.argmax(
            logits,
            dim=1
        )

        all_preds.extend(
            preds.cpu().numpy()
        )

        all_labels.extend(
            labels.cpu().numpy()
        )

    loss = (
        running_loss /
        len(train_loader)
    )

    acc = accuracy_score(
        all_labels,
        all_preds
    )

    return loss, acc

# ============================================================
# VALIDATION
# ============================================================

def validate():

    fusion_model.eval()

    running_loss = 0

    all_preds = []
    all_labels = []

    with torch.no_grad():

        for batch in val_loader:

            audio = batch[
                "audio"
            ].to(DEVICE)

            input_ids = batch[
                "input_ids"
            ].to(DEVICE)

            attention_mask = batch[
                "attention_mask"
            ].to(DEVICE)

            labels = batch[
                "label"
            ].to(DEVICE)

            _, speech_embedding = speech_model(
                audio
            )

            _, text_embedding = text_model(
                input_ids,
                attention_mask
            )

            logits = fusion_model(
                speech_embedding,
                text_embedding
            )

            loss = criterion(
                logits,
                labels
            )

            running_loss += loss.item()

            preds = torch.argmax(
                logits,
                dim=1
            )

            all_preds.extend(
                preds.cpu().numpy()
            )

            all_labels.extend(
                labels.cpu().numpy()
            )

    loss = (
        running_loss /
        len(val_loader)
    )

    acc = accuracy_score(
        all_labels,
        all_preds
    )

    return loss, acc

# ============================================================
# TRAIN FUSION
# ============================================================

best_val_acc = 0

patience_counter = 0

best_model_path = os.path.join(
    RESULTS_DIR,
    "fusion_model.pth"
)

for epoch in range(
    NUM_EPOCHS
):

    train_loss, train_acc = (
        train_one_epoch()
    )

    val_loss, val_acc = (
        validate()
    )

    print(
        f"Epoch {epoch+1}/{NUM_EPOCHS} | "
        f"Train Acc={train_acc:.4f} | "
        f"Val Acc={val_acc:.4f}"
    )

    if val_acc > best_val_acc:

        best_val_acc = val_acc

        patience_counter = 0

        torch.save(
            fusion_model.state_dict(),
            best_model_path
        )

    else:

        patience_counter += 1

    if patience_counter >= PATIENCE:

        print(
            "Early Stopping Triggered"
        )

        break

print(
    "\nBest Validation Accuracy:",
    best_val_acc
)

# ============================================================
# SAVE BEST CONFIG
# ============================================================

fusion_config = {
    "learning_rate": LEARNING_RATE,
    "epochs": NUM_EPOCHS,
    "best_validation_accuracy": best_val_acc
}

config_path = os.path.join(
    RESULTS_DIR,
    "fusion_best_config.json"
)

with open(
    config_path,
    "w"
) as f:

    json.dump(
        fusion_config,
        f,
        indent=4
    )

print("Fusion Config Saved")

# ============================================================
# LOAD BEST FUSION MODEL
# ============================================================

best_fusion_model = FusionEmotionModel(
    dropout=0.3,
    num_classes=NUM_CLASSES
)

best_fusion_model.load_state_dict(
    torch.load(
        best_model_path,
        map_location=DEVICE
    )
)

best_fusion_model = best_fusion_model.to(
    DEVICE
)

best_fusion_model.eval()

print("Best Fusion Model Loaded")

# ============================================================
# TEST EVALUATION
# ============================================================

all_preds = []
all_labels = []

all_embeddings = []

with torch.no_grad():

    for batch in tqdm(test_loader):

        audio = batch["audio"].to(DEVICE)

        input_ids = batch[
            "input_ids"
        ].to(DEVICE)

        attention_mask = batch[
            "attention_mask"
        ].to(DEVICE)

        labels = batch[
            "label"
        ].to(DEVICE)

        # Speech Embedding

        _, speech_embedding = speech_model(
            audio
        )

        # Text Embedding

        _, text_embedding = text_model(
            input_ids,
            attention_mask
        )

        logits = best_fusion_model(
            speech_embedding,
            text_embedding
        )

        preds = torch.argmax(
            logits,
            dim=1
        )

        all_preds.extend(
            preds.cpu().numpy()
        )

        all_labels.extend(
            labels.cpu().numpy()
        )

        fused_embedding = torch.cat(
            [
                speech_embedding,
                text_embedding
            ],
            dim=1
        )

        all_embeddings.extend(
            fused_embedding.cpu().numpy()
        )

# ============================================================
# METRICS
# ============================================================

test_acc = accuracy_score(
    all_labels,
    all_preds
)

test_precision = precision_score(
    all_labels,
    all_preds,
    average="weighted",
    zero_division=0
)

test_recall = recall_score(
    all_labels,
    all_preds,
    average="weighted",
    zero_division=0
)

test_f1 = f1_score(
    all_labels,
    all_preds,
    average="weighted",
    zero_division=0
)

print("\nTest Accuracy:", test_acc)
print("Test Precision:", test_precision)
print("Test Recall:", test_recall)
print("Test F1:", test_f1)

# ============================================================
# CLASSIFICATION REPORT
# ============================================================

report = classification_report(
    all_labels,
    all_preds,
    target_names=[
        idx_to_emotion[i]
        for i in range(NUM_CLASSES)
    ],
    zero_division=0
)

print(report)

report_path = os.path.join(
    RESULTS_DIR,
    "fusion_classification_report.txt"
)

with open(
    report_path,
    "w"
) as f:

    f.write(report)

print(
    "Classification Report Saved"
)

# ============================================================
# CONFUSION MATRIX
# ============================================================

cm = confusion_matrix(
    all_labels,
    all_preds
)

plt.figure(figsize=(10,8))

sns.heatmap(
    cm,
    annot=True,
    fmt="d",
    cmap="Blues",
    xticklabels=list(
        emotion_map.keys()
    ),
    yticklabels=list(
        emotion_map.keys()
    )
)

plt.title(
    "Fusion Confusion Matrix"
)

plt.xlabel(
    "Predicted"
)

plt.ylabel(
    "Actual"
)

cm_path = os.path.join(
    RESULTS_DIR,
    "fusion_confusion_matrix.png"
)

plt.savefig(
    cm_path,
    bbox_inches="tight"
)

plt.show()

print(
    "Confusion Matrix Saved"
)

# ============================================================
# ACCURACY TABLE
# ============================================================

results_df = pd.DataFrame(
    {
        "Metric": [
            "Accuracy",
            "Precision",
            "Recall",
            "F1 Score"
        ],
        "Value": [
            test_acc,
            test_precision,
            test_recall,
            test_f1
        ]
    }
)

csv_path = os.path.join(
    RESULTS_DIR,
    "fusion_accuracy.csv"
)

results_df.to_csv(
    csv_path,
    index=False
)

print(results_df)

print(
    "Accuracy Table Saved"
)

# ============================================================
# TSNE
# ============================================================

embeddings_np = np.array(
    all_embeddings
)

labels_np = np.array(
    all_labels
)

tsne = TSNE(
    n_components=2,
    random_state=42,
    perplexity=30
)

tsne_features = tsne.fit_transform(
    embeddings_np
)

plt.figure(figsize=(10,8))

scatter = plt.scatter(
    tsne_features[:,0],
    tsne_features[:,1],
    c=labels_np,
    cmap="tab10"
)

plt.colorbar(scatter)

plt.title(
    "Fusion t-SNE"
)

tsne_path = os.path.join(
    RESULTS_DIR,
    "fusion_tsne.png"
)

plt.savefig(
    tsne_path,
    bbox_inches="tight"
)

plt.show()

print(
    "Fusion t-SNE Saved"
)

# ============================================================
# VERIFY OUTPUTS
# ============================================================

print(
    os.listdir(
        RESULTS_DIR
    )
)

